spring.application.name=projeto-pessoal-back

spring.datasource.url=${DATABASE_URL:}
spring.datasource.username=${DATABASE_USERNAME:}
spring.datasource.password=${DATABASE_PASSWORD:}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.certificates.storage-dir=${CERTIFICATES_STORAGE_DIR:}
